### ISSUE TITLE
Error loading image - Unable to connect to backend

### ISSUE THREAD

**Issue by yuri25** [Shahiem/ckeditor-plugin#4]
![octo](https://cloud.githubusercontent.com/assets/253228/4874905/577c00b6-6278-11e4-9199-ec1fde6800d2.jpg)

**Comment by yuri25** [comment]
It is true in a few days hacked the site is due to features allow proc_open .... That's bad luck :(

**Comment by Shahiem** [comment]
Elfinder is removed. It's replaced with the octobercms mediamanger. So, this problem is solved.
